@isTest
public class IFBTestConfig_IntQuestionCategoryMap {
	
	public static List<IFB_InterviewQuestionCategoryMap__c> getSettings() {
		List<IFB_InterviewQuestionCategoryMap__c> settings = new List<IFB_InterviewQuestionCategoryMap__c>();

		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'SA|CSG - Recruiter Prescreen', Interview_Record_Type_Name__c = 'CSG - Recruiter Prescreen', Position__c = 'SA', Question_Category__c = 'SA Prescreen'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'Default', Question_Category__c = 'Technical Question'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|CSG - Manager Prescreen', Interview_Record_Type_Name__c = 'CSG - Manager Prescreen', Position__c = 'Default', Question_Category__c = 'TA Prescreen'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'PM|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'PM', Question_Category__c = 'PM Question'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|CSG - Consulting/Second', Interview_Record_Type_Name__c = 'CSG - Consulting/Second', Position__c = 'Default', Question_Category__c = 'Consulting Question'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|CSG - Panel Interview', Interview_Record_Type_Name__c = 'CSG - Panel Interview', Position__c = 'Default', Question_Category__c = 'Panel Question'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'PM|CSG - Recruiter Prescreen', Interview_Record_Type_Name__c = 'CSG - Recruiter Prescreen', Position__c = 'PM', Question_Category__c = 'PM Prescreen'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|CSG - Recruiter Prescreen', Interview_Record_Type_Name__c = 'CSG - Recruiter Prescreen', Position__c = 'Default', Question_Category__c = 'TA Prescreen'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'BA|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'BA', Question_Category__c = 'Content Question'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Engagement Mgr|CSG - Consulting/Se', Interview_Record_Type_Name__c = 'CSG - Consulting/Second', Position__c = 'Engagement Mgr', Question_Category__c = 'EM Consulting'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Engagement Mgr|CSG - Technical/Fir', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'Engagement Mgr', Question_Category__c = 'EM Technical'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'SA|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'SA', Question_Category__c = 'SA Technical'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Success Partner|CSG - Consulting/S', Interview_Record_Type_Name__c = 'CSG - Consulting/Second', Position__c = 'Success Partner', Question_Category__c = 'SP Consulting'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Success Partner|CSG - Technical/Fi', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'Success Partner', Question_Category__c = 'SP Technical'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Associate PA|CSG - Consulting/Seco', Interview_Record_Type_Name__c = 'CSG - Consulting/Second', Position__c = 'Associate PA', Question_Category__c = 'APA Consulting'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Associate PA|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'Associate PA', Question_Category__c = 'APA Technical'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'SM|CSG - Consulting/Second', Interview_Record_Type_Name__c = 'CSG - Consulting/Second', Position__c = 'SM', Question_Category__c = 'SM Second'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'SM|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'SM', Question_Category__c = 'SM First'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Associate BA|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'Associate BA', Question_Category__c = 'Content Question'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'PA|CSG - Technical/First', Interview_Record_Type_Name__c = 'CSG - Technical/First', Position__c = 'PA', Question_Category__c = 'PA Technical'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'CBU|Sales - 1st Stage', Interview_Record_Type_Name__c = 'Sales - 1st stage interview (HM phone screen/onsite, chrono/panel)', Position__c = 'CBU', Question_Category__c = 'Sales - 1st stage interview (HM phone screen/onsite, chrono/panel)'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|Sales - 1st stage', Interview_Record_Type_Name__c = 'Sales - 1st stage interview (HM phone screen/onsite, chrono/panel)', Position__c = 'Default', Question_Category__c = 'Sales - 1st stage interview (HM phone screen/onsite, chrono/panel)'));
		settings.add(new IFB_InterviewQuestionCategoryMap__c(Name = 'Default|Sales - AE Presentation', Interview_Record_Type_Name__c = 'Sales - AE Presentation/Final Stage', Position__c = 'Default', Question_Category__c = 'Sales - AE Presentation/Final Stage'));
		
		return settings;
	}

}