public with sharing class NHW_WDR_CandidateTriggerHandler implements WDR_CommonTriggerHandler {
	/**
    * @description Interface method for handling before insert method.
    *
    **/
    public void beforeInsert(){ 
    }

    /**
    * @description Interface method for handling after insert method.
    * 
    **/
    public void afterInsert(){
    }

    /**
    * @description Interface method for handling before update method.
    * //Populate do not send and do Validations on preboarding & do not send NHW flags
    **/
    public void beforeUpdate(){
    }

    /**
    * @description Interface method for handling after update method.
    **/
    public void afterUpdate(){
        
    }
    /**
    * @description Interface method for handling before delete method.
    *
    **/
    public void beforeDelete(){ 
    }
    
    /**
    * @description Interface method for handling after delete method.
    *
    **/
    public void afterDelete(){
    }

    /**
    * @description Interface method for handling after undelete method.
    *
    **/
    public void afterUnDelete(){
    }
    
}