public class NHWRecruitmentPlacementDataMapper implements NHWRecruitmentDataMapper {

    public static sObject getPlacementRecByID(Id Placementid){

        return null;
    }
    public static list<sobject> getPlacementRecsByHiringMgerIds(set<id> userids){
          return null;
    }
    public NHWRecruitmentModel getNHWRecruitmentModelObjectById(Id PlacementId){
               
            return null;
   
    }
    public list<NHWRecruitmentModel> getAllNHWRecruitmentModelObjectsForMger(set<id> userids){

            return null;
    }

    public static NHWRecruitmentModel mapPlacementToModelObject(sObject placementRec){
         
        return null;
            
    }

}