@isTest
public class talentMP_TestUtilValues {
    
    //Role Names
    public static final String TALENTMP_CUSTOMER_USERROLE_NAME = 'Salesforce.com Customer User';
    
    //Role Type
    public static final String TALENTMP_ROLETYPE_NONE = 'None';
    
    //UserProfile Names
    public static final String TALENTMP_COMMUNITY_PORTAL_PROFILE = 'Customer Portal Manager Custom';
    public static final String TALENTMP_SYSADMIN_PROFILE = 'System Administrator';
    //Permissionset Names
    public static final String TALENTMP_PERMSET = 'Talent_Marketplace';
    
    //User Email Address
    public static final String TALENTMP_PORTAL_USER_EMAIL = 'talentMP_0@community.com';
    
    //Email Suffix for Portal user
    public static final String EMAILSUFFIX_PORTALUSER = '@community.com';
    //Email Suffix for test user
    public static final String EMAILSUFFIX_TESTUSER = '@test.com';
        

}