/**
* @author Apuroop Gadde
* @date 06-22-2017
* @group TriggerHandlers
* @description Trigger handler for the WDR_Job object that handles the trigger events from the WDR side 
*/
public with sharing class WDR_JobTriggerHandler implements WDR_CommonTriggerHandler{
    /**
    * @description Constructor to cast the trigger variables from generics to WDR_Job objects.
    **/
    public WDR_JobTriggerHandler() {
    }

    /**
    * @description Method to handle the before insert event on the WDR_Job object
    **/
    public void beforeInsert() {
    }

    /**
    * @description Method to handle the after insert event on the WDR_Job object
    **/
    public void afterInsert() {
    }

    /**
    * @description Method to handle the before update event on the WDR_Job object
    **/
    public void beforeUpdate(){
    }

    /**
    * @description Method to handle the after update event on the WDR_Job object
    **/
    public void afterUpdate() {
    
    }

    /**
    * @description Method to handle the before delete event on the WDR_Job object
    **/
    public void beforeDelete() {
    }

    /**
    * @description Method to handle the after delete event on the WDR_Job object
    **/
    public void afterDelete() {
    }

    /**
    * @description Method to handle the after undelete event on the WDR_Job object
    **/
    public void afterUnDelete() {
    }
}