/**
* @author Apuroop Gadde
* @date 06-22-2017
* @group TriggerHandlers
* @description Trigger handler for the WDR_Application object that handles the trigger events from the WDR side 
*/
public with sharing class WDR_ApplicationTriggerHandler implements WDR_CommonTriggerHandler{
    /**
    * @description Constructor to cast the trigger variables from generics to WDR_Application objects.
    **/
    public WDR_ApplicationTriggerHandler() {
        
    }

    /**
    * @description Method to handle the before insert event on the WDR_Application object
    **/
    public void beforeInsert() {

        
    }

    /**
    * @description Method to handle the after insert event on the WDR_Application object
    **/
    public void afterInsert() {
    }

    /**
    * @description Method to handle the before update event on the WDR_Application object
    **/
    public void beforeUpdate(){
    }

    /**
    * @description Method to handle the after update event on the WDR_Application object
    **/
    public void afterUpdate() {
    }

    /**
    * @description Method to handle the before delete event on the WDR_Application object
    **/
    public void beforeDelete() {
    }

    /**
    * @description Method to handle the after delete event on the WDR_Application object
    **/
    public void afterDelete() {
    }

    /**
    * @description Method to handle the after undelete event on the WDR_Application object
    **/
    public void afterUnDelete() {
    }

}